// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrH1xor2diQ5ykEl2UHf4rslODPzQpzDU',
    appId: '1:953505839149:web:ced4df4697a171456160a4',
    messagingSenderId: '953505839149',
    projectId: 'utfpr-solicitacoes-app-c23fa',
    authDomain: 'utfpr-solicitacoes-app-c23fa.firebaseapp.com',
    storageBucket: 'utfpr-solicitacoes-app-c23fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRTP4TF6q15mdh5KQev52YtTONzcjQCoo',
    appId: '1:953505839149:android:836de4145bd2429a6160a4',
    messagingSenderId: '953505839149',
    projectId: 'utfpr-solicitacoes-app-c23fa',
    storageBucket: 'utfpr-solicitacoes-app-c23fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqJffZ9FKSOiGijmAV30NkWoeyGUXiog',
    appId: '1:953505839149:ios:8cdb68c2ff9bb5b26160a4',
    messagingSenderId: '953505839149',
    projectId: 'utfpr-solicitacoes-app-c23fa',
    storageBucket: 'utfpr-solicitacoes-app-c23fa.firebasestorage.app',
    iosBundleId: 'com.example.utfprSolicitacoesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqJffZ9FKSOiGijmAV30NkWoeyGUXiog',
    appId: '1:953505839149:ios:8cdb68c2ff9bb5b26160a4',
    messagingSenderId: '953505839149',
    projectId: 'utfpr-solicitacoes-app-c23fa',
    storageBucket: 'utfpr-solicitacoes-app-c23fa.firebasestorage.app',
    iosBundleId: 'com.example.utfprSolicitacoesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrH1xor2diQ5ykEl2UHf4rslODPzQpzDU',
    appId: '1:953505839149:web:57584e847fa56d0a6160a4',
    messagingSenderId: '953505839149',
    projectId: 'utfpr-solicitacoes-app-c23fa',
    authDomain: 'utfpr-solicitacoes-app-c23fa.firebaseapp.com',
    storageBucket: 'utfpr-solicitacoes-app-c23fa.firebasestorage.app',
  );
}
